### ISSUE TITLE
Beyond SW camp first player MINI PROJ #3 - FE 완료 보고 일정 안내

### ISSUE THREAD

**Issue by pySatellite** [beyond-sw-camp/be01_3nd_mini-project#5]
# 최종발표
1. 24.02.07(수) 오후 4시 30 ~ 최종발표 
2. 3,2,5,1,4 조 순으로 발표 
3. 발표시간 4분, 1분의 질의응답 ( 4분 초과 시 화면 및 마이크 꺼짐 ) 
4. 발표 자료는 팀 github repo 첨부 
5. 데모는 local 컴퓨터가 아닌 github page, firebase, fly.io 등에 배포 
6. (4) (5) 항에 대하여 아래 댓글로 4시 20분까지 제출

# 회고
- 좋은점, 나쁜점, 개선할점을 도출하여 각팀 애자일 코치가 진행(2/8 4교시) - 회고후 팀 회식 권고 ~
- 회고 이후 결과를 각팀 레포에 올려두고(사진찍어서, 사진으로 식별 가능하지 않으면 적어서) 아래 코맨트로 #회고 타이틀 달고 이슈 링크를 달아주세요. 동시에 팀 레포 메인 README.md 에도 업데이트 !!!
- 회고 진행은 AC, 점심 식사 가자! 라고 외치는 사람은 PM, 기록은 형상담당자 가 해주세요.

# 단원 평가
- 오후 5시 30분 부터 20분간 진행

![image](https://github.com/beyond-sw-camp/be01-101/assets/87309910/67999d6d-7fa2-4148-b62f-282501733a3f)

**Comment by INAUGURATE-Ryong** [comment]
# scheduFlow
- express 배포 서버 : https://scheduflow-express.fly.dev/schedules
- json-server : https://scheduflow-json-server.fly.dev/schedules
- Vue 배포 서버 : https://scheduflow.web.app/
- npm module : https://www.npmjs.com/package/scheduflow
- 발표자료 : https://github.com/beyond-sw-camp/be01_3nd_5team/blob/main/ScheduFlow%20%EB%B0%9C%ED%91%9C%EC%9E%90%EB%A3%8C.pdf
- 회고링크 : https://github.com/beyond-sw-camp/be01_3nd_mini-project/issues/7

**Comment by Jaelinny** [comment]
## be01_3nd_2team: Knowledge Nexus
- github repo : https://github.com/beyond-sw-camp/be01_3nd_2team
- json-server : https://mmmmmmm-dry-glade-6852.fly.dev/
- Vue 배포 서버 : https://team2-kms.web.app/
- npm module : https://www.npmjs.com/package/hw-knowledge-management
- 회고 링크: https://github.com/beyond-sw-camp/be01_3nd_mini-project/issues/6

**Comment by Afresh2** [comment]
[be01_3nd_3team]
팀명 : Ramen-Syndrome
json-server : https://ramen-syndrome-jsonserver.fly.dev/sales
Vue 배포 서버 : https://ramen-syndrome-91acc.web.app/

**Comment by hyunsungJoo** [comment]
## Team Workflow-Ease

- json-server : https://hris-json-server.fly.dev/
- Vue 배포 서버 : https://workflow-ease-123.web.app/dashboard-default
- 회고 링크 : https://github.com/beyond-sw-camp/be01_3nd_mini-project/issues/8

**Comment by Afresh2** [comment]
## [3team]Ramen-Syndrome
- repo : https://github.com/beyond-sw-camp/be01_3nd_Ramen-Syndrome
- json-server : https://ramen-syndrome-jsonserver.fly.dev/
- firebase 배포 : https://ramen-syndrome-91acc.web.app/

**Comment by dhkdtld37** [comment]
# be01_3nd_1team - SCMC

- Express : https://r4-vueti.fly.dev/
- Json-server : https://[r1-json-server.fly.dev](https://r1-json-server.fly.dev/)/
- Vue 배포 서버 : https://scmc-b3b8f.web.app/
- 발표 자료 : https://github.com/beyond-sw-camp/be01_3nd_1team/blob/main/1%EC%A1%B0-3rd_Mini-project%20%20.pdf

**Comment by pySatellite** [comment]
![LGTM](https://i.lgtm.fun/2p75.gif)
